language: node_js
node_js:
  - "8"
install:
  - yarn install
script:
  - yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: 'dist'
    github_token: $GITHUB_TOKEN
    on:
      branch: master
